# Generated by Django 5.0.4 on 2024-04-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itme',
            new_name='Item',
        ),
    ]
