# Generated by Django 5.0.4 on 2024-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_item_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_price',
        ),
        migrations.AddField(
            model_name='item',
            name='item_ingre',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
